#!/bin/bash

set -ex
pwd
env

echo "Login to CF"
cf api $PWS_API --skip-ssl-validation

cf login -u $PWS_USER -p $PWS_PWD -o "$PWS_ORG" -s "$PWS_SPACE"

cf apps

pwd
ls -lart

cf push environment -s windows2012R2 -b hwc_buildpack -p concourse-pipeline-samples/ViewEnvironment/

cf apps

echo "App started"
