#!/bin/bash

set -xe
echo "inside appmanifestfile"

sed "s/APPNAME/$(cat $PWS_APP_SUFFIX/" ./concourse-pipeline-samples/manifests/manifest.yml > ./app-manifest-output/manifest.yml

cat ./app-manifest-output/manifest.yml
