---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
- name: resource-git-onboarding_api

outputs:
- name: jarFile

run:
  path: resource-git-onboarding_api/ci/tasks/build.sh