---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: latest

inputs:
- name: resource-git-onboarding_api

outputs:
- name: current-app-info

run:
  path: resource-git-onboarding_api/ci/tasks/current-app-get-info.sh