---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
- name: resource-git-onboarding_api

run:
  path: resource-git-onboarding_api/ci/tasks/run-test.sh
