groups:
- name: main
  jobs:
  - deploy-app

resources:
- name: concourse-pipeline-samples
  type: git
  source:
    branch: master
    uri: {{git-url}}
    username: {{git-username}}
    private_key: {{git-private-key}}
- name: PWS
  type: cf
  source:
    api: {{pws-api}}
    organization: {{pws-organization}}
    username: {{deploy-username}}
    password: {{deploy-password}}
    skip_cert_check: true
    space: {{pws-space}}

jobs:
- name: deploy-app
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
  - task: prepare-app-manifest
    file: concourse-pipeline-samples/DotnetApp/ci/tasks/app-manifest-prep.yml
    params:
      PWS_APP_SUFFIX: {{pws-app-suffix}}
  - put: PWS
    params:
      manifest: app-manifest-output/manifest.yml
      path: concourse-pipeline-samples/DotnetApp/bgd-app
      