groups:
- name: main
  jobs:
  - deploy-app

resources:
- name: concourse-pipeline-samples
  type: git
  source:
    branch: master
    uri: https://github.com/sandhyass2017/DotnetApp.git
    username: sandhyass2017
    password: sep@2017

jobs:
- name: deploy-app
  serial: true
  public: true
  plan:
  - get: concourse-pipeline-samples
    trigger: true
  - task: prepare-app-manifest
    file: concourse-pipeline-samples/ci/tasks/app-manifest-prep.yml
    params:
      PWS_API: {{pws-api}}
      PWS_ORG: {{pws-organization}}
      PWS_USER: {{deploy-username}}
      PWS_PWD: {{deploy-password}}
      PWS_SPACE: {{pws-space}}
      